#!perl

# This program only exists to figure out why perl 5.12.0 RC1 hangs when
# trying to test PUT in Test::WWW::Mechanize.

use strict;
use warnings;

use WWW::Mechanize;

my $server      = HangServer->new;
$server->background;
my $server_root = $server->root;

my $mech = WWW::Mechanize->new;

GOOD_GET: {
    my $goodlinks = "$server_root/goodlinks.html";
    $mech->get( $goodlinks );
    $mech->success or die "Unable to get $goodlinks";
    print "=== GET content ===\n";
    print $mech->content, "\n";
    print "=== GET content ===\n";
}

print "\n\nHit enter to do a PUT.  You can also go elsewhere and connect to $server_root";
my $f = <>;

GOOD_GET: {
    my $scraps = "$server_root/scraps.html";
    $mech->put( $scraps );
    {use Data::Dumper; local $Data::Dumper::Sortkeys=1;
        print Dumper( $mech )}
    print "=== PUT content ===\n";
    print $mech->content, "\n";
    print "=== PUT content ===\n";
    print 'Success in the PUT? ', ($mech->success ? 'YES' : 'NO'), '\n';
}

print "\n\nHit enter to down the server";
$f = <>;

$server->stop;

print "Server stopped\n";

exit;


package HangServer;

use warnings;
use strict;

use base 'HTTP::Server::Simple::CGI';

use Carp ();

our $pid;

sub new {
    my $class = shift;

    die 'An instance of HangServer has already been started.' if $pid;

    # XXX This should really be a random port.
    return $class->SUPER::new(13432, @_);
}

sub handle_request {
    my $self = shift;
    my $cgi  = shift;

    use Data::Dumper; local $Data::Dumper::Sortkeys=1;
    my $response = Dumper($cgi);
    $response .= '$cgi->path_info is [' . $cgi->path_info . ']';

    print "HTTP/1.0 200 OK\r\n";
    print "Content-Type: text/html\r\nContent-Length: ", length($response), "\r\n\r\n", $response;
    return;
}

sub background {
    my $self = shift;

    $pid = $self->SUPER::background()
        or Carp::confess( q{Can't start the test server} );

    sleep 1; # background() may come back prematurely, so give it a second to fire up

    return $pid;
}

sub root {
    my $self = shift;
    my $port = $self->port;

    return "http://localhost:$port";
}

sub stop {
    if ( $pid ) {
        kill( 9, $pid ) unless $^S;
        undef $pid;
    }

    return;
}

1;
